//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS_Presentacion.ServicioDetalle {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetallePrestamoEntidad", Namespace="http://schemas.datacontract.org/2004/07/DAS_Entidades")]
    [System.SerializableAttribute()]
    public partial class DetallePrestamoEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADO_EJE_DETField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADO_F_EJEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADO_I_EJEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FEC_DEV_DETField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_DETField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_LIBROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_PRESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBS_DETField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USU_REC_DETField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO_EJE_DET {
            get {
                return this.ESTADO_EJE_DETField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADO_EJE_DETField, value) != true)) {
                    this.ESTADO_EJE_DETField = value;
                    this.RaisePropertyChanged("ESTADO_EJE_DET");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO_F_EJE {
            get {
                return this.ESTADO_F_EJEField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADO_F_EJEField, value) != true)) {
                    this.ESTADO_F_EJEField = value;
                    this.RaisePropertyChanged("ESTADO_F_EJE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO_I_EJE {
            get {
                return this.ESTADO_I_EJEField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADO_I_EJEField, value) != true)) {
                    this.ESTADO_I_EJEField = value;
                    this.RaisePropertyChanged("ESTADO_I_EJE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FEC_DEV_DET {
            get {
                return this.FEC_DEV_DETField;
            }
            set {
                if ((this.FEC_DEV_DETField.Equals(value) != true)) {
                    this.FEC_DEV_DETField = value;
                    this.RaisePropertyChanged("FEC_DEV_DET");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_DET {
            get {
                return this.ID_DETField;
            }
            set {
                if ((this.ID_DETField.Equals(value) != true)) {
                    this.ID_DETField = value;
                    this.RaisePropertyChanged("ID_DET");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_LIBRO {
            get {
                return this.ID_LIBROField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_LIBROField, value) != true)) {
                    this.ID_LIBROField = value;
                    this.RaisePropertyChanged("ID_LIBRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PRES {
            get {
                return this.ID_PRESField;
            }
            set {
                if ((this.ID_PRESField.Equals(value) != true)) {
                    this.ID_PRESField = value;
                    this.RaisePropertyChanged("ID_PRES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBS_DET {
            get {
                return this.OBS_DETField;
            }
            set {
                if ((object.ReferenceEquals(this.OBS_DETField, value) != true)) {
                    this.OBS_DETField = value;
                    this.RaisePropertyChanged("OBS_DET");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USU_REC_DET {
            get {
                return this.USU_REC_DETField;
            }
            set {
                if ((object.ReferenceEquals(this.USU_REC_DETField, value) != true)) {
                    this.USU_REC_DETField = value;
                    this.RaisePropertyChanged("USU_REC_DET");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioDetalle.IServicioDetalle")]
    public interface IServicioDetalle {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/add", ReplyAction="http://tempuri.org/IServicioDetalle/addResponse")]
        DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad add(DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/add", ReplyAction="http://tempuri.org/IServicioDetalle/addResponse")]
        System.Threading.Tasks.Task<DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad> addAsync(DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/edit", ReplyAction="http://tempuri.org/IServicioDetalle/editResponse")]
        bool edit(DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/edit", ReplyAction="http://tempuri.org/IServicioDetalle/editResponse")]
        System.Threading.Tasks.Task<bool> editAsync(DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/delete", ReplyAction="http://tempuri.org/IServicioDetalle/deleteResponse")]
        bool delete(DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/delete", ReplyAction="http://tempuri.org/IServicioDetalle/deleteResponse")]
        System.Threading.Tasks.Task<bool> deleteAsync(DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/traerDetalle", ReplyAction="http://tempuri.org/IServicioDetalle/traerDetalleResponse")]
        DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad traerDetalle(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/traerDetalle", ReplyAction="http://tempuri.org/IServicioDetalle/traerDetalleResponse")]
        System.Threading.Tasks.Task<DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad> traerDetalleAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/detallePorPrestamo", ReplyAction="http://tempuri.org/IServicioDetalle/detallePorPrestamoResponse")]
        DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[] detallePorPrestamo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/detallePorPrestamo", ReplyAction="http://tempuri.org/IServicioDetalle/detallePorPrestamoResponse")]
        System.Threading.Tasks.Task<DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[]> detallePorPrestamoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/buscar", ReplyAction="http://tempuri.org/IServicioDetalle/buscarResponse")]
        DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[] buscar(string busqueda, int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/buscar", ReplyAction="http://tempuri.org/IServicioDetalle/buscarResponse")]
        System.Threading.Tasks.Task<DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[]> buscarAsync(string busqueda, int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/buscarPendientesIdPrestamo", ReplyAction="http://tempuri.org/IServicioDetalle/buscarPendientesIdPrestamoResponse")]
        DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[] buscarPendientesIdPrestamo(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/buscarPendientesIdPrestamo", ReplyAction="http://tempuri.org/IServicioDetalle/buscarPendientesIdPrestamoResponse")]
        System.Threading.Tasks.Task<DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[]> buscarPendientesIdPrestamoAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/buscarByIdPrestamoAll", ReplyAction="http://tempuri.org/IServicioDetalle/buscarByIdPrestamoAllResponse")]
        DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[] buscarByIdPrestamoAll(int prestamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetalle/buscarByIdPrestamoAll", ReplyAction="http://tempuri.org/IServicioDetalle/buscarByIdPrestamoAllResponse")]
        System.Threading.Tasks.Task<DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[]> buscarByIdPrestamoAllAsync(int prestamo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioDetalleChannel : DAS_Presentacion.ServicioDetalle.IServicioDetalle, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDetalleClient : System.ServiceModel.ClientBase<DAS_Presentacion.ServicioDetalle.IServicioDetalle>, DAS_Presentacion.ServicioDetalle.IServicioDetalle {
        
        public ServicioDetalleClient() {
        }
        
        public ServicioDetalleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDetalleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDetalleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDetalleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad add(DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad obj) {
            return base.Channel.add(obj);
        }
        
        public System.Threading.Tasks.Task<DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad> addAsync(DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad obj) {
            return base.Channel.addAsync(obj);
        }
        
        public bool edit(DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad obj) {
            return base.Channel.edit(obj);
        }
        
        public System.Threading.Tasks.Task<bool> editAsync(DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad obj) {
            return base.Channel.editAsync(obj);
        }
        
        public bool delete(DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad obj) {
            return base.Channel.delete(obj);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAsync(DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad obj) {
            return base.Channel.deleteAsync(obj);
        }
        
        public DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad traerDetalle(int id) {
            return base.Channel.traerDetalle(id);
        }
        
        public System.Threading.Tasks.Task<DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad> traerDetalleAsync(int id) {
            return base.Channel.traerDetalleAsync(id);
        }
        
        public DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[] detallePorPrestamo(int id) {
            return base.Channel.detallePorPrestamo(id);
        }
        
        public System.Threading.Tasks.Task<DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[]> detallePorPrestamoAsync(int id) {
            return base.Channel.detallePorPrestamoAsync(id);
        }
        
        public DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[] buscar(string busqueda, int value) {
            return base.Channel.buscar(busqueda, value);
        }
        
        public System.Threading.Tasks.Task<DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[]> buscarAsync(string busqueda, int value) {
            return base.Channel.buscarAsync(busqueda, value);
        }
        
        public DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[] buscarPendientesIdPrestamo(int value) {
            return base.Channel.buscarPendientesIdPrestamo(value);
        }
        
        public System.Threading.Tasks.Task<DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[]> buscarPendientesIdPrestamoAsync(int value) {
            return base.Channel.buscarPendientesIdPrestamoAsync(value);
        }
        
        public DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[] buscarByIdPrestamoAll(int prestamo) {
            return base.Channel.buscarByIdPrestamoAll(prestamo);
        }
        
        public System.Threading.Tasks.Task<DAS_Presentacion.ServicioDetalle.DetallePrestamoEntidad[]> buscarByIdPrestamoAllAsync(int prestamo) {
            return base.Channel.buscarByIdPrestamoAllAsync(prestamo);
        }
    }
}
