//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_prestamos
    {
        public int ID_DET { get; set; }
        public string ID_LIBRO { get; set; }
        public Nullable<int> ID_PRES { get; set; }
        public string ESTADO_I_EJE { get; set; }
        public string ESTADO_F_EJE { get; set; }
        public string FEC_DEV_DET { get; set; }
        public string USU_REC_DET { get; set; }
        public string OBS_DET { get; set; }
        public string ESTADO_EJE_DET { get; set; }
    
        public virtual libro libro { get; set; }
        public virtual prestamo prestamo { get; set; }
        public virtual usuarios_sistema usuarios_sistema { get; set; }
    }
}
