//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_prestamo
    {
        public int ID_DET { get; set; }
        public Nullable<int> ID_PRES { get; set; }
        public string ID_LIBRO { get; set; }
        public Nullable<System.DateTime> FEC_DET { get; set; }
        public string EST_LIB_DET { get; set; }
        public Nullable<int> DIAS_RETRASO_DET { get; set; }
        public Nullable<System.DateTime> FEC_PRES_DET { get; set; }
        public Nullable<System.DateTime> FEC_DEV_DET { get; set; }
        public string USU_PRES_LIB_DET { get; set; }
        public string status { get; set; }
    }
}
