//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesABCF : DbContext
    {
        public EntitiesABCF()
            : base("name=EntitiesABCF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<detalle_prestamos> detalle_prestamos { get; set; }
        public virtual DbSet<estudiante> estudiante { get; set; }
        public virtual DbSet<libro> libro { get; set; }
        public virtual DbSet<prestamo> prestamo { get; set; }
        public virtual DbSet<usuarios_sistema> usuarios_sistema { get; set; }
    }
}
