//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamos
    {
        public int ID_PRES { get; set; }
        public Nullable<System.DateTime> FECHA_PRES { get; set; }
        public string ID_EST { get; set; }
        public string status { get; set; }
    }
}
