//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios_sistema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios_sistema()
        {
            this.detalle_prestamos = new HashSet<detalle_prestamos>();
            this.libro = new HashSet<libro>();
            this.prestamo = new HashSet<prestamo>();
        }
    
        public string CED_USU { get; set; }
        public string NOM_USU { get; set; }
        public string APE_USU { get; set; }
        public string SEXO_USU { get; set; }
        public string EMAIL_USU { get; set; }
        public string TELF_USU { get; set; }
        public string TIPO_USU { get; set; }
        public string CONTRA_USU { get; set; }
        public Nullable<System.DateTime> FEC_ING_SIS { get; set; }
        public string ESTADO_USU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_prestamos> detalle_prestamos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<libro> libro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prestamo> prestamo { get; set; }
    }
}
