//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS_Presentacion.ServicioPrestamo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioPrestamo.IServicioPrestamo")]
    public interface IServicioPrestamo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/add", ReplyAction="http://tempuri.org/IServicioPrestamo/addResponse")]
        DAS_Entidades.PrestamoEntidad add(DAS_Entidades.PrestamoEntidad obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/add", ReplyAction="http://tempuri.org/IServicioPrestamo/addResponse")]
        System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad> addAsync(DAS_Entidades.PrestamoEntidad obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/edit", ReplyAction="http://tempuri.org/IServicioPrestamo/editResponse")]
        bool edit(DAS_Entidades.PrestamoEntidad obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/edit", ReplyAction="http://tempuri.org/IServicioPrestamo/editResponse")]
        System.Threading.Tasks.Task<bool> editAsync(DAS_Entidades.PrestamoEntidad obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/delete", ReplyAction="http://tempuri.org/IServicioPrestamo/deleteResponse")]
        bool delete(DAS_Entidades.PrestamoEntidad obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/delete", ReplyAction="http://tempuri.org/IServicioPrestamo/deleteResponse")]
        System.Threading.Tasks.Task<bool> deleteAsync(DAS_Entidades.PrestamoEntidad obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/obtenerPrestamoID", ReplyAction="http://tempuri.org/IServicioPrestamo/obtenerPrestamoIDResponse")]
        DAS_Entidades.PrestamoEntidad obtenerPrestamoID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/obtenerPrestamoID", ReplyAction="http://tempuri.org/IServicioPrestamo/obtenerPrestamoIDResponse")]
        System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad> obtenerPrestamoIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/getPendiente", ReplyAction="http://tempuri.org/IServicioPrestamo/getPendienteResponse")]
        DAS_Entidades.PrestamoEntidad[] getPendiente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/getPendiente", ReplyAction="http://tempuri.org/IServicioPrestamo/getPendienteResponse")]
        System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad[]> getPendienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/getPendientePersona", ReplyAction="http://tempuri.org/IServicioPrestamo/getPendientePersonaResponse")]
        DAS_Entidades.PrestamoEntidad[] getPendientePersona(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/getPendientePersona", ReplyAction="http://tempuri.org/IServicioPrestamo/getPendientePersonaResponse")]
        System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad[]> getPendientePersonaAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/buscar", ReplyAction="http://tempuri.org/IServicioPrestamo/buscarResponse")]
        DAS_Entidades.PrestamoEntidad[] buscar(string busqueda, int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/buscar", ReplyAction="http://tempuri.org/IServicioPrestamo/buscarResponse")]
        System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad[]> buscarAsync(string busqueda, int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/updateState", ReplyAction="http://tempuri.org/IServicioPrestamo/updateStateResponse")]
        void updateState(DAS_Entidades.PrestamoEntidad prestamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/updateState", ReplyAction="http://tempuri.org/IServicioPrestamo/updateStateResponse")]
        System.Threading.Tasks.Task updateStateAsync(DAS_Entidades.PrestamoEntidad prestamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/getByDateRange", ReplyAction="http://tempuri.org/IServicioPrestamo/getByDateRangeResponse")]
        DAS_Entidades.PrestamoEntidad[] getByDateRange(System.DateTime initDate, System.DateTime endDate, int option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/getByDateRange", ReplyAction="http://tempuri.org/IServicioPrestamo/getByDateRangeResponse")]
        System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad[]> getByDateRangeAsync(System.DateTime initDate, System.DateTime endDate, int option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/getPrestamos30", ReplyAction="http://tempuri.org/IServicioPrestamo/getPrestamos30Response")]
        DAS_Entidades.PrestamoEntidad[] getPrestamos30();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/getPrestamos30", ReplyAction="http://tempuri.org/IServicioPrestamo/getPrestamos30Response")]
        System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad[]> getPrestamos30Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/obtenerPrestamos", ReplyAction="http://tempuri.org/IServicioPrestamo/obtenerPrestamosResponse")]
        DAS_Entidades.PrestamoEntidad[] obtenerPrestamos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrestamo/obtenerPrestamos", ReplyAction="http://tempuri.org/IServicioPrestamo/obtenerPrestamosResponse")]
        System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad[]> obtenerPrestamosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPrestamoChannel : DAS_Presentacion.ServicioPrestamo.IServicioPrestamo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPrestamoClient : System.ServiceModel.ClientBase<DAS_Presentacion.ServicioPrestamo.IServicioPrestamo>, DAS_Presentacion.ServicioPrestamo.IServicioPrestamo {
        
        public ServicioPrestamoClient() {
        }
        
        public ServicioPrestamoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPrestamoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPrestamoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPrestamoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DAS_Entidades.PrestamoEntidad add(DAS_Entidades.PrestamoEntidad obj) {
            return base.Channel.add(obj);
        }
        
        public System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad> addAsync(DAS_Entidades.PrestamoEntidad obj) {
            return base.Channel.addAsync(obj);
        }
        
        public bool edit(DAS_Entidades.PrestamoEntidad obj) {
            return base.Channel.edit(obj);
        }
        
        public System.Threading.Tasks.Task<bool> editAsync(DAS_Entidades.PrestamoEntidad obj) {
            return base.Channel.editAsync(obj);
        }
        
        public bool delete(DAS_Entidades.PrestamoEntidad obj) {
            return base.Channel.delete(obj);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAsync(DAS_Entidades.PrestamoEntidad obj) {
            return base.Channel.deleteAsync(obj);
        }
        
        public DAS_Entidades.PrestamoEntidad obtenerPrestamoID(int id) {
            return base.Channel.obtenerPrestamoID(id);
        }
        
        public System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad> obtenerPrestamoIDAsync(int id) {
            return base.Channel.obtenerPrestamoIDAsync(id);
        }
        
        public DAS_Entidades.PrestamoEntidad[] getPendiente() {
            return base.Channel.getPendiente();
        }
        
        public System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad[]> getPendienteAsync() {
            return base.Channel.getPendienteAsync();
        }
        
        public DAS_Entidades.PrestamoEntidad[] getPendientePersona(string id) {
            return base.Channel.getPendientePersona(id);
        }
        
        public System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad[]> getPendientePersonaAsync(string id) {
            return base.Channel.getPendientePersonaAsync(id);
        }
        
        public DAS_Entidades.PrestamoEntidad[] buscar(string busqueda, int value) {
            return base.Channel.buscar(busqueda, value);
        }
        
        public System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad[]> buscarAsync(string busqueda, int value) {
            return base.Channel.buscarAsync(busqueda, value);
        }
        
        public void updateState(DAS_Entidades.PrestamoEntidad prestamo) {
            base.Channel.updateState(prestamo);
        }
        
        public System.Threading.Tasks.Task updateStateAsync(DAS_Entidades.PrestamoEntidad prestamo) {
            return base.Channel.updateStateAsync(prestamo);
        }
        
        public DAS_Entidades.PrestamoEntidad[] getByDateRange(System.DateTime initDate, System.DateTime endDate, int option) {
            return base.Channel.getByDateRange(initDate, endDate, option);
        }
        
        public System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad[]> getByDateRangeAsync(System.DateTime initDate, System.DateTime endDate, int option) {
            return base.Channel.getByDateRangeAsync(initDate, endDate, option);
        }
        
        public DAS_Entidades.PrestamoEntidad[] getPrestamos30() {
            return base.Channel.getPrestamos30();
        }
        
        public System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad[]> getPrestamos30Async() {
            return base.Channel.getPrestamos30Async();
        }
        
        public DAS_Entidades.PrestamoEntidad[] obtenerPrestamos() {
            return base.Channel.obtenerPrestamos();
        }
        
        public System.Threading.Tasks.Task<DAS_Entidades.PrestamoEntidad[]> obtenerPrestamosAsync() {
            return base.Channel.obtenerPrestamosAsync();
        }
    }
}
